language: python
python: "2.7"
install:
- virtualenv test-env --no-setuptools
- mkdir -p buildout-cache/downloads
- test-env/bin/python bootstrap.py -c travis.cfg -v 2.2.1
- bin/buildout -N -t 5 -c travis.cfg
script:
  - make tests
  - make coverage

after_success:
 - pip install python-coveralls==2.4.0 || true
 - coveralls || true

notifications:
  irc:
    channels:
      - "irc.freenode.org#affinitic"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
